Chore/test audio bars
devlucky/react-audio-vis pull request #14
Opened 2017-05-27 00:56 UTC by majames

Test (allthethings)

2017-05-27 01:08 UTC, majames commented on README.md
> +[![Build Status](https://travis-ci.org/devlucky/react-audio-vis.svg?branch=master)](https://travis-ci.org/devlucky/react-audio-vis)
Update badges to point at devlucky

2017-05-27 01:08 UTC, majames commented on src/analyser/index.tsx
> +  getBucketedByteFrequencyData = (maxNumBuckets: number): Array<number> => {
Move logic for bucketing frequency data into `Analyser` (other visualisations can use this)

2017-05-28 21:52 UTC, zzarcon requested changes

2017-05-28 21:52 UTC, zzarcon commented on src/bars/index.test.tsx
> +      expect(addEventListener.mock.calls[2][0]).toEqual('ended');
Those cases are gold!

2017-05-28 21:52 UTC, zzarcon commented on src/bars/index.test.tsx
> +      expect(canvasContext.clearRect).toHaveBeenLastCalledWith(0 , 0, 400, 400);
Not sure if this ```it``` is giving us some value or we are getting to deep here. Like from the outside, seeing ```0 , 0, 400, 400``` looks really weird

2017-05-28 21:52 UTC, zzarcon commented on src/bars/index.test.tsx
> +      expect(canvasContext.fillRect).toHaveBeenCalledWith(0, 400 - firstBarHeight, firstBarWidth, firstBarHeight);
Same thing here as before, I do like the ```draws the correct number of bars to the canvas``` test and I think we should keep it, but I will prefer to see something like:

```javascript

expect(wrapper.instance().drawSingleBar).toHaveBeenCalledTimes(expectedNumberOfDrawedBars);
```

What do you think? I don't think doing such calculations in the testsuite is the way to go, I think we should try to abstract that more

2017-05-28 21:52 UTC, zzarcon commented on src/bars/index.tsx
> +    const barValues = analyser.getBucketedByteFrequencyData(maxNumBarsToDraw);
Nice one

2017-05-29 09:50 UTC, majames commented on src/bars/index.test.tsx
> +      expect(canvasContext.clearRect).toHaveBeenLastCalledWith(0 , 0, 400, 400);
Yeah. I defs think it looks a little weird... but I do like testing the logic for clearing the canvas.

How about I use *explaining variables*? Like:

`const canvasDefaultWidth = 400;`
`const canvasDefaultHeight = 400;`

2017-06-01 06:26 UTC, zzarcon approved these changes

2017-06-01 06:26 UTC, merged